autoload colors;
colors
fg[brown]='\033[38;5;130m'

function random_icon() {
    local icons=(
        "$fg[black]$reset_color"
        "$fg[black]$reset_color"
        "$fg[black]ﮏ$reset_color"
        "$fg[black]礼$reset_color"
        "$fg[black]$reset_color"
        "$fg[black]$reset_color"
        "$fg[black]$reset_color"

        "$fg[blue]$reset_color"
        "$fg[blue]$reset_color"
        "$fg[blue]$reset_color"
        "$fg[blue]﫶$reset_color"
        "$fg[blue]$reset_color"
        "$fg[blue]$reset_color"
        "$fg[blue]$reset_color"

        "$fg[brown]$reset_color"
        "$fg[brown]$reset_color"
        "$fg[brown]$reset_color"
        "$fg[brown]$reset_color"

        "$fg[cyan]$reset_color"
        "$fg[cyan]$reset_color"
        "$fg[cyan]$reset_color"
        "$fg[cyan]$reset_color"
        "$fg[cyan]$reset_color"
        "$fg[cyan]$reset_color"
        "$fg[cyan]$reset_color"

        "$fg[green]$reset_color"
        "$fg[green]$reset_color"
        "$fg[green]$reset_color"
        "$fg[green]$reset_color"
        "$fg[green]$reset_color"
        "$fg[green]$reset_color"
        "$fg[green]$reset_color"
        "$fg[green]$reset_color"
        "$fg[green]滑$reset_color"
        "$fg[green]$reset_color"
        "$fg[green]$reset_color"

        "$fg[magenta]$reset_color"
        "$fg[magenta]$reset_color"
        "$fg[magenta]$reset_color"
        "$fg[magenta]$reset_color"
        "$fg[magenta]$reset_color"
        "$fg[magenta]$reset_color"
        "$fg[magenta]豈$reset_color"

        "$fg[red]$reset_color"
        "$fg[red]$reset_color"
        "$fg[red]$reset_color"
        "$fg[red]$reset_color"
        "$fg[red]異$reset_color"
        "$fg[red]$reset_color"
        "$fg[red]$reset_color"
        "$fg[red]$reset_color"
        "$fg[red]$reset_color"
        "$fg[red]$reset_color"
        "$fg[red]$reset_color"
        "$fg[red]$reset_color"
        "$fg[red]嗢$reset_color"
        "$fg[red]$reset_color"

        "$fg[white]$reset_color"
        "$fg[white]$reset_color"
        "$fg[white]$reset_color"
        "$fg[white]$reset_color"
        "$fg[white]$reset_color"
        "$fg[white]$reset_color"
        "$fg[white]$reset_color"
        "$fg[white]$reset_color"
        "$fg[white]$reset_color"

        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
        "$fg[yellow]$reset_color"
    )
    echo -e "${icons[$RANDOM % ${#icons[@]}]}"
}
