[
  "affinity-designer"
  "affinity-photo"
  "alt-tab"
  "balenaetcher"
  "bartender"
  "chatgpt"
  "cleanmymac"
  "drawio"
  "firefox"
  # "google-drive" #Broken
  "handbrake"
  "imageoptim"
  "itsycal"
  "iterm2"
  "keepassxc"
  "microsoft-outlook"
  "microsoft-teams"
  "music-decoy"
  "namechanger"
  "obs"
  # "obs-ndi"
  "plex"
  "rectangle"
  "screens-connect"
  "spotmenu"
  "slack"
  # "steam" #Broken
  "stats"
  "whatsapp"
]